# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bad79f6bc4c4a7054a2f031222b8ce24cb0410a8070149fcbc5dc12aa0a04b9eb05c2a8cdace71e64ba3058002ad29e185f0dcb225e14a6b2bcc74ffcb013c8a

test:
  secret_key_base: 8190bc8e02483af42fb7ec14eb6eaba44065529daf2dad58a9df8e0811196b4c13cf6aa6106944ba3eb0e020fe0cd0b34619e2c301f7bd367b1202b2b92b4d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
